### ISSUE TITLE
filter = missing?

### ISSUE THREAD

**Issue by ghost** [atnetws/fail2ban-log4j#6]
With sudo fail2ban-client restart i got 

'filter' not defined in 'apache-jndi'. Using default one: ''
 No filter set for jail apache-jndi

**Comment by atnetws** [comment]
I've tested the config on Debian systems, where the filter name defaults to the section name instead of an empty one, so if you call a section apache-jndi, fail2ban will search for a filter definition file with that excact name.  

Anyway, I'll add a filter assignment, as it increases the overall compatibility.

**Comment by atnetws** [comment]
Fixed in 0.0.5
